// Contains some kind of database for the details of the hotels

export const InfoData = [
  {
    id: 0,
    imageSource:(require('../../assets/Images/hotel1.jpeg')),
    name: 'Emeralda De Hotel',
    location: 'Paris, France',
    distance: '20 km',
    price: '1 000 000',
    bedroomNum: 2,
    bathroomNum: 1,
  },
  {
    id: 1,
    imageSource:(require('../../assets/Images/hotel2.jpeg')),
    name: 'President Hotel',
    location: 'Paris, France',
    distance: '18 km',
    price: '1 500 000',
    bedroomNum: 3,
    bathroomNum: 2,
  },
  {
    id: 2,
    imageSource:(require('../../assets/Images/hotel3.jpeg')),
    name: 'Palms Casino',
    location: 'Amsterdam, Netherlands',
    distance: '16 km',
    price: '2 000 000',
    bedroomNum: 4,
    bathroomNum: 3,
  },
  {
    id: 3,
    imageSource:(require('../../assets/Images/hotel4.jpeg')),
    name: 'Palazzo Versace',
    location: 'Rome, Italy',
    distance: '10 km',
    price: '1 500 000',
    bedroomNum: 6,
    bathroomNum: 3,
  },
  {
    id: 4,
    imageSource:(require('../../assets/Images/hotel5.jpeg')),
    name: 'The Venetian',
    location: 'Rotterdam, Netherlands',
    distance: '22 km',
    price: '1 000 000',
    bedroomNum: 3,
    bathroomNum: 3,
  },
  {
    id: 5,
    imageSource:(require('../../assets/Images/hotel6.jpeg')),
    name: 'Bird Rock',
    location: 'Istanbul, Turkiye',
    distance: '21 km',
    price: '2 500 000',
    bedroomNum: 6,
    bathroomNum: 4,
  },
  {
    id: 6,
    imageSource:(require('../../assets/Images/hotel7.jpeg')),
    name: 'Martinez Hotel',
    location: 'London, England',
    distance: '20 km',
    price: '1 500 000',
    bedroomNum: 3,
    bathroomNum: 2,
  },
  {
    id: 7,
    imageSource:(require('../../assets/Images/hotel8.jpeg')),
    name: 'Palazzo Versace',
    location: 'Paris, France',
    distance: '15 km',
    price: '2 000 000',
    bedroomNum: 5,
    bathroomNum: 3,
  },
  {
    id: 8,
    imageSource:(require('../../assets/Images/hotel9.jpeg')),
    name: 'Faena Hotel',
    location: 'London, England',
    distance: '19 km',
    price: '1 500 000',
    bedroomNum: 4,
    bathroomNum: 4,
  },
];